<a href="https://colab.research.google.com/github/sydoky/Data-Preprocessing/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started,Importing the Libraries,Importing the Dataset,Taking care of Missing Data,Encoding Categorical Data,Splitting the dataset into the Training set and Test set,Feature Scaling

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Dataset

In [6]:
dataset=pd.read_csv("/content/Data.csv")

dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
X1=dataset.drop("Purchased", axis=1)

In [8]:
X=dataset.iloc[:,:-1].values

In [9]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
y=dataset.iloc[:,-1].values

In [11]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Take care of Missing data

In [14]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [15]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(),[0])], remainder="passthrough")
X=np.array(ct.fit_transform(X))

# Encoding The dependent Variable 

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

In [22]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

# Feature Scaling 

In [24]:
X_train

array([[1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

In [28]:
X_train

array([[1.0, 0.0, 0.0, -0.21741694455872748, 0.3006011885204433],
       [0.0, 1.0, 0.0, -1.1702703363639333, -0.8071260258698517],
       [0.0, 0.0, 1.0, 0.02457756764576933, -0.9775455973145125],
       [0.0, 1.0, 0.0, 0.1909487947863607, 0.026036323415156753],
       [0.0, 0.0, 1.0, -0.08129503144369808, -0.21065752581353903],
       [0.0, 1.0, 0.0, 1.5521679259366548, 1.6639577600777296],
       [0.0, 0.0, 1.0, -1.5786360757090214, -1.318384740203834],
       [1.0, 0.0, 0.0, 1.279924099706596, 1.323118617188408]],
      dtype=object)